# Generated by Django 3.0.3 on 2020-03-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='parameters',
            field=models.CharField(choices=[('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentsApp.Address')), ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentsApp.Room'))], default='None', max_length=10),
        ),
    ]
