# Generated by Django 3.0.3 on 2020-03-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentsApp', '0002_apartments_parameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartments',
            options={'ordering': ('name',), 'verbose_name': 'Apartments', 'verbose_name_plural': 'Apartments'},
        ),
    ]
