# Generated by Django 3.0.3 on 2020-03-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentsApp', '0003_auto_20200304_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartments',
            options={'ordering': ('id',), 'verbose_name': 'Apartments', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='address',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='room',
        ),
        migrations.AlterField(
            model_name='apartments',
            name='parameters',
            field=models.CharField(choices=[('address', 'address'), ('room', 'room')], default='None', max_length=10),
        ),
    ]
