# Generated by Django 3.0.3 on 2020-03-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentsApp', '0004_auto_20200304_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApartmentsApp.Apartments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApartmentsApp.Apartments'),
            preserve_default=False,
        ),
    ]
