# Generated by Django 3.0.4 on 2020-03-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentsApp', '0007_auto_20200305_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='squire_size',
            field=models.FloatField(default=0.0),
        ),
    ]
